### ISSUE TITLE
What happened to the Python 2.7 openmm-dev packages?

### ISSUE THREAD

**Issue by swails** [omnia-md/openmm-dev#10]
They seem to have recently vanished.  Did I just catch it at an inopportune time and it's in the process of uploading or something? https://travis-ci.org/ParmEd/ParmEd/jobs/69052179#L373

**Comment by jchodera** [comment]
This has been happening because of binstar issues. Jenkins forces reupload causing package deletion, but then binstar gives an error, leaving the package erased.  See #5

**Comment by jchodera** [comment]
I will try to figure out a way to work around this as soon as I get home (45 min)

**Comment by jchodera** [comment]
`openmm-dev` package building is disabled now that there are recent `linux` and `osx` packages posted.  See #5 for the ongoing drama.  Closing this now since it is a duplicate of #5.
