### ISSUE TITLE
Python 3.4 package for Linux disappeared

### ISSUE THREAD

**Issue by swails** [omnia-md/openmm-dev#14]
Any chance of getting it back?  It's made my ParmEd test builds start failing...

**Comment by rmcgibbo** [comment]
Lol: https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant-2/108/console

**Comment by rmcgibbo** [comment]
Same persistent SSL error that seems to happen periodically with that jenkins server, but it only happens after the packages have first been removed and the new ones are getting uploaded.

**Comment by swails** [comment]
Suck.

**Comment by rmcgibbo** [comment]
The best bet, unless anyone knows how to fix the error (I previously had thought that switching to miniconda3 would fix the issue, but it doesn't) is probably just to retrigger the build in jenkins.

**Comment by jchodera** [comment]
I find the best bet is to manually delete all the packages then rebuild on Jenkins, but this is going to keep happening until we find a way to fix it.

Could this just be an outdated OpenSSL system package or something?

**Comment by rmcgibbo** [comment]
Because this one is openmm-dev, I don't think you need to delete anything before hitting the rebuild button.

**Comment by jchodera** [comment]
Triggered.

**Comment by jchodera** [comment]
This is still failing sporadically on `osx`:

```
TEST END: openmm-dev-7.0.0.dev0-py27_0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/conda-bld/osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

+ binstar --quiet -t **** upload --force -u omnia miniconda/conda-bld/osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2
Using binstar api site https://api.anaconda.org
[warning] Distribution osx-64/openmm-dev-7.0.0.dev0-py27_0.tar.bz2 already exists ... removing 
[BinstarError] Invalid dist_id 
Traceback (most recent call last):
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/bin/binstar", line 6, in <module>
    sys.exit(main())
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 204, in main
    callback=upload_print_callback(args))
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 434, in upload
    self._check_response(res)
  File "/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
BinstarError: (u'Invalid dist_id', 400)
```

**Comment by swails** [comment]
Yep, which is bringing down my ParmEd build on Travis again...

Can you retrigger the OS X builds?

**Comment by jchodera** [comment]
Retriggered.

Any idea how we can make this more robust?  I can't obviously keep triggering builds manually.

**Comment by jchodera** [comment]
What about the `conda config --set anaconda_upload yes` setting?  Is there some way we can configure this to automatically upload when builds are successful?  This would require logging into binstar or somehow setting the binstar upload token.

**Comment by jchodera** [comment]
Alternatively, can we force delete the package on binstar just before we upload?

**Comment by rmcgibbo** [comment]
I haven't seen a `BinstarError: (u'Invalid dist_id', 400)` before. Have you checked on the continuum github? There might be a bug you can file there.

**Comment by swails** [comment]
Py3.4 package disappeared again... sigh.

**Comment by jchodera** [comment]
> I haven't seen a BinstarError: (u'Invalid dist_id', 400) before. Have you checked on the continuum github? There might be a bug you can file there.

Isn't that the same error I've been seeing for a while, just printed in a different form?

I reported it here originally:
https://github.com/Anaconda-Server/docs.anaconda.org/issues/84

but that wasn't being monitored, so I reported it here:
https://github.com/Anaconda-Server/binstar/issues/173

which has been deleted.

Anyone know where the real issue tracker is?

**Comment by jchodera** [comment]
> Py3.4 package disappeared again... sigh.

I retriggered the build, but obviously, this is not a sustainable solution.  Any further ideas?

**Comment by rmcgibbo** [comment]
https://twitter.com/stephenakearns/status/648541292322881536 said to file bugs at https://github.com/Anaconda-Server/docs.anaconda.org/issues

**Comment by jchodera** [comment]
Posted here: https://github.com/Anaconda-Server/docs.anaconda.org/issues/122
