### ISSUE TITLE
Upload to openmm-dev packages to binstar using git commit hash summary?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/openmm-dev#3]
I can't recall if we previously experimented with using the git has commit summary in naming the version of the package when pushing to binstar, but if it was possible to both grab the "latest dev version" and specific git commit hash versions, this would make life a lot easier.

**Comment by rmcgibbo** [comment]
I think there's a serious storage problem here. Each binary package is ~10M. Storing built binaries for every single commit hash seems expensive. I think if you want to install old  snapshots of the code, it's not unreasonable to checkout the appropriate git commit and compile it.

**Comment by jchodera** [comment]
What about the most recent 10 or 20?

I think we have 100GB to play with now.

git-bisect and recompilation is indeed very useful, but given how long
OpenMM takes to compile inside a VM, it is also a painfully slow process.

Perhaps the solution is to keep the builds somewhere; just not on binstar.

**Comment by rmcgibbo** [comment]
Obviously if you want to do this, go for it. If the use case here is for git-bisect debugging, you could also do your debugging on a faster machine, e.g. with `make -j16` -- but there are a lot of ways to skin this cat.

It seems to me that we already spend many many hours maintaining build infrastructure. I'm personally not that eager to add more work to that pile.

**Comment by jchodera** [comment]
> Obviously if you want to do this, go for it. If the use case here is for git-bisect debugging, you could also do your debugging on a faster machine, e.g. with make -j16 -- but there are a lot of ways to skin this cat.

Tried that.  Didn't have `clang` installed.  Waited for sysadmin to install `clang`.  

> It seems to me that we already spend many many hours maintaining build infrastructure. I'm personally not that eager to add more work to that pile.

Agreed.  We need to simplify the build infrastructure---it's already taking a huge amount of effort to maintain.

That's why I'm excited about `binstar build`...

**Comment by jchodera** [comment]
I think @rmcgibbo's nice [avi work](https://github.com/pandegroup/openmm/issues/984) may obviate the need for this.
