### ISSUE TITLE
Is it safe to remove openmm-pr-780.patch?

### ISSUE THREAD

**Issue by jchodera** [omnia-md/openmm-dev#6]
@peastman: Do we still need the [`openmm-pr-780.patch`](https://github.com/omnia-md/openmm-dev/blob/master/openmm-pr-780.patch) for building the current git heads of `OpenMM`?

**Comment by rmcgibbo** [comment]
no, it's not being used by anything.

**Comment by jchodera** [comment]
Thanks!
